### ISSUE TITLE
Import failure with SymPy 1.9

### ISSUE THREAD

**Issue by alexmalins** [radioactivedecay/radioactivedecay#50]
Importing radioactivedecay currently fails with the most recent version of SymPy ([v1.9](https://github.com/sympy/sympy/wiki/Release-Notes-for-1.9), released 9 Oct 2021):

```
>>> import radioactivedecay
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\rd_39\lib\site-packages\radioactivedecay\__init__.py", line 21, in <module>
    from radioactivedecay.decaydata import DecayData, DEFAULTDATA
  File "C:\ProgramData\Anaconda3\envs\rd_39\lib\site-packages\radioactivedecay\decaydata.py", line 620, in <module>
    DEFAULTDATA = DecayData("icrp107_ame2020_nubase2020", load_sympy=True)
  File "C:\ProgramData\Anaconda3\envs\rd_39\lib\site-packages\radioactivedecay\decaydata.py", line 416, in __init__
    atomic_masses = _load_package_pickle_file(
  File "C:\ProgramData\Anaconda3\envs\rd_39\lib\site-packages\radioactivedecay\decaydata.py", line 82, in _load_package_pickle_file
    return pickle.load(file)
AttributeError: 'Rational' object has no attribute '__dict__'
```

The error is related to the loading of pickled SymPy data files, which were created with version 1.8 of SymPy. I am currently investigating the best fix moving forward.

A temporary solution is to rollback to SymPy v1.8 in your local environment.

Note this error is also the reason the latest release (v0.4.4) of radioactivedecay is [not yet available](https://github.com/conda-forge/radioactivedecay-feedstock/pull/10) on conda-forge.

**Comment by radioactivedecay-github** [comment]
Looks like this became an issue once again as of SymPy-1.10. The source of the problem is [this](https://github.com/radioactivedecay/radioactivedecay/blob/main/radioactivedecay/decaydata.py#L766) line in [decaydata.py](https://github.com/radioactivedecay/radioactivedecay/blob/main/radioactivedecay/decaydata.py):

```py
sympy_pickle_version = "1.9" if sympy.__version__ >= "1.9" else "1.8"
```

The check for version greater than or equal to "1.9" fails for "1.10" because:

```py
>>> "1.10" >= "1.9"
False
```

Here is a simple solution based on [this](https://stackoverflow.com/a/11887825) answer on SO. Replace the [following lines](https://github.com/radioactivedecay/radioactivedecay/blob/main/radioactivedecay/decaydata.py#L765-L766):

```py
    if load_sympy:
        sympy_pickle_version = "1.9" if sympy.__version__ >= "1.9" else "1.8"
```

with:

```py
      versiontuple = lambda v: tuple(map(int, (v.split("."))))                               
      if load_sympy:                                                                         
          sympy_pickle_version = "1.9" if versiontuple(sympy.__version__) >= versiontuple("1.9") else "1.8" 
```
