### ISSUE TITLE
Missing Isotopes/Isotope Data

### ISSUE THREAD

**Issue by JWingUtk** [radioactivedecay/radioactivedecay#65]
Hello. I've found this package rather useful but have encountered an issue with the nuclide data being incomplete or unexpectedly missing. When adding certain isotopes and metastable states to an inventory, I will get the following message. 

[isotope]  is not a valid nuclide in icrp107_ame2020_nubase2020 decay dataset.

Upon checking the icrp107 report I can see that these isotopes are supposed to be present. V49 and V52 for example.

I am currently running radioactivedecay under Python 3.8 on Windows 10 with Radioactivedecay version 0.4.8 and installed via pip.

Any help would be appreciated, thank you.

**Comment by alexmalins** [comment]
Hi @JWingUtk

This is strange. Also running Python 3.8 on Windows 10 with Radioactivedecay version 0.4.8 installed via pip, those isotopes work fine for me. 

The only thing I can think of is the nuclide string is case sensitive, so this works ("V49"):

```
>>> import radioactivedecay as rd
>>> rd.Inventory({"V49": 1.0})
Inventory activities (Bq): {'V-49': 1.0}, decay dataset: icrp107_ame2020_nubase2020
```

but this doesn't ("v49"):
```
>>> rd.Inventory({"v49": 1.0})
Inventory activities (Bq): {'V-49': 1.0}, decay dataset: icrp107_ame2020_nubase2020
....
ValueError: v49 is not a valid nuclide in icrp107_ame2020_nubase2020 decay dataset.
```

If this isn't your issue, can you please paste the command and full error Traceback you are finding?

**Comment by JWingUtk** [comment]
It's been puzzling me for a bit. Case sensitivity is not the cause of my error. Below is the traceback I get trying to run my waste classification script.

<img width="692" alt="Error" src="https://user-images.githubusercontent.com/97312558/152278991-bcba1eb5-c329-41c9-b1d3-799f106dc77b.PNG">

**Comment by alexmalins** [comment]
@JWingUtk 

Thanks! I think the issue is there is a white-space character at the end of your nuclide input string, i.e. it is "V49 " not "V49". This reproduces the same error on my machine:

```
>>> rd.InventoryHP({'V49 ': 1.0}, 'Bq')
...
ValueError: V49  is not a valid nuclide in icrp107_ame2020_nubase2020 decay dataset.
```

This is a bug - the package really should be able to cope with leading or trailing white-spaces in nuclide names like this. It should also be able to cope with case sensitivity issues like in my last message, i.e. accept "V49" or "v49".

The fixes for these issues are quite simple & would be great first issues. I noticed you recently joined GitHub - if you are interested in Python & contributing to open source software, I'd be happy to help mentor you on how to fix problems like this via the Pull Request system? If not, no worries, I'll work on a fix tomorrow.

In the meantime you should be able to fix the problem locally in your script by striping out the white-space characters from your nuclide strings. You can do this using a Dictionary comprehension on your `Hp_inv_t0` dictionary like so before supplying it to the `InventoryHP` constructor:

```
Hp_inv_t0 = {nuc.strip(): act for nuc, act in Hp_inv_t0.items()}
```

Let me know what you think!

**Comment by JWingUtk** [comment]
I'll patch it up on my end for now, but I am absolutely interested in contributing and being mentored on fixing problems via the pull request system. I feel pretty bad about not noticing the blank space at all, lost many hours to troubleshooting before submitting the issue here haha.

**Comment by alexmalins** [comment]
@JWingUtk That's great. Please drop me an email at alex.malins at DELETETHISgmail.com then we can get you up an running!

**Comment by JWingUtk** [comment]
@alexmalins I believe I sent an email to the correct address. Let me know if you don't see anything!

**Comment by alexmalins** [comment]
Thanks got it!

**Comment by alexmalins** [comment]
PR #72 & release v0.4.11 solve this issue

**Comment by alexmalins** [comment]
Hey @GallegoSav - this issue is similar to this one: #80 
The problem is one of naming: we should better describe the default dataset as just ICRP-107. Only the radionuclides in that dataset are included. Nubase2020 was just use to supplement atomic mass data that wasn't in ICRP-107. So all the nuclides in nubase2020 that don't also exist in ICRP-107 are not included in this package currently, sorry 😢
